### ISSUE TITLE
不能正常使用

### ISSUE THREAD

**Issue by MaxCrazy1101** [wjx-git/IllegalTextDetection#1]
训练fasttext正常
另一个训练不出来

**Comment by dtMndas** [comment]
请问，fasttext 的版本是多少呢 ？

**Comment by wjx-git** [comment]
> 训练fasttext正常 另一个训练不出来

请问训练不出来是报什么错呢？

**Comment by MaxCrazy1101** [comment]
就是我直接运行train_roberta.py 最后根本没有保存结果
看了一下train函数中的global_step只有28步

**Comment by MaxCrazy1101** [comment]
> 请问，fasttext 的版本是多少呢 ？

0.9.2

**Comment by wjx-git** [comment]
> 就是我直接运行train_roberta.py 最后根本没有保存结果 看了一下train函数中的global_step只有28步

默认参数中是运行1500个step才会保存，也就是--save_steps==1500，你的训练step太少了。也可以将--save_steps设为10，这样global_step只有28个step的情况下也能保存两次。

**Comment by MaxCrazy1101** [comment]
那训练的步数在哪里改呢，训练28步出来结果不正确啊，对`傻逼`的检查是false

**Comment by wjx-git** [comment]
> 那训练的步数在哪里改呢，训练28步出来结果不正确啊，对`傻逼`的检查是false
num_train_epochs是设置训练批次的超参数，默认是4。你训练时只有28个step说明你的训练数据量太少了，你还是先补充数据吧。
