### ISSUE TITLE
RoBERTa无法正确判断

### ISSUE THREAD

**Issue by dkesdb** [wjx-git/IllegalTextDetection#3]
您好，我clone了您的代码，没有修改参数，但是RoBERTa模型无法给出正常的判断，在训练的时候每个epoch打印出的label为1的精确率和召回率都是0，label为0时上述数值没有变化。在输入一些脏话的时候RoBERTa也无法给出正确判断，调了很久没有思路，想问一下您的意见，谢谢！

**Comment by buddingworld** [comment]
有解决的吗 我也是这个问题 一直是返回1
